# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build_phase
    jobs:
      - job: A1
        displayName: Build the app
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        - script: |
            yarn
            yarn build
          displayName: 'yarn install and build'
  - stage: run_tests
    jobs:
      - job: e2e
        displayName: End_to_end_tests
        steps:
        - script: |
            yarn
            yarn test
          displayName: 'yarn test'
  - stage: deploy
    jobs:
      - deployment: DeployStaging
        displayName: Deploy to staging environment
        pool:
          vmImage: 'Ubuntu-latest'
        environment: 'Staging'
        strategy:
          runOnce:
            deploy:
              steps:
              - script: mkdir nestJS-Service